version: '3.6'

services:

  serpentapi:
    build:
      context: ./services/serpentapi
      dockerfile: Dockerfile-dev
    volumes:
      - './services/serpentapi:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@serpentapi-db:5432/serpentapi_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@serpentapi-db:5432/serpentapi_test
      - SECRET_KEY=serpent_key
    depends_on:
      - serpentapi-db

  serpentapi-db:
    build:
      context: ./services/serpentapi/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_SERPENT_SERVICE_URL=${REACT_APP_SERPENT_SERVICE_URL}
    depends_on:
      - serpentapi

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-dev
    volumes:
        - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.json
    depends_on:
      - serpentapi

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - serpentapi
      - client
