version: '3.6'

services:

  serpentapi:
    build:
      context: ./services/serpentapi
      dockerfile: Dockerfile-stage
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@serpentapi-db:5432/serpentapi_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@serpentapi-db:5432/serpentapi_test
      - SECRET_KEY=serpent_key
    depends_on:
      - serpentapi-db

  serpentapi-db:
    build:
      context: ./services/serpentapi/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
      args:
        - NODE_ENV=production
        - REACT_APP_SERPENT_SERVICE_URL=${REACT_APP_SERPENT_SERVICE_URL}
    expose:
      - 80
    depends_on:
      - serpentapi

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-stage
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - serpentapi

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports:
      - 80:80
    depends_on:
      - serpentapi
      - client
