# base image
from python:3.7-slim

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
WORKDIR /usr/src/app

# copy requirements files
COPY ./Pipfile /usr/src/app
COPY ./Pipfile.lock /usr/src/app

# setup pipenv for requirements
RUN pip install pipenv
RUN pipenv install --system --deploy

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint.sh"]